export const LOGIN_MESSAGES = {
  otpSentPrefix: "OTP sent to",
  toastOtpSent: "OTP sent",
  toastLoginSuccess: "Login successful",
  toastOtpResent: "OTP resent",
  errorInvalidMobile: "Enter valid mobile number",
  errorInvalidOtp: "Enter valid OTP",
} as const;

export const REGISTER_MESSAGES = {
  toastBasicInfoSaved: "Basic info saved",
  toastRegistrationDetailsSaved: "Registration details saved",
  toastRegistrationComplete: "Registration complete",
  toastOtpResent: "OTP resent",
  errorFixHighlightedFields: "Please correct highlighted fields",
  errorCompleteRequiredDetails: "Please complete all required details",
  errorInvalidMobile: "Enter a valid mobile number",
  errorInvalidEmail: "Valid email is required",
  errorInvalidOtp: "Enter valid OTP",
  languageRequiredError: "Select at least one language",
  termsText: "By clicking submit, you accept the Terms and Conditions.",
  otpSentForRegistrationPrefix: "OTP sent for registration confirmation to",
} as const;

export const AUTH_SCHEMA_MESSAGES = {
  mobileInvalid: "Enter a valid 10-digit mobile number",
  otpInvalid: "Enter a valid 6-digit OTP",
  fullNameRequired: "Full name is required",
  emailInvalid: "Valid email is required",
  experienceRequired: "Experience is required",
  languagesRequired: "Select at least one language",
  serviceLocationRequired: "Service location is required",
} as const;

export const KYC_MESSAGES = {
  ribbonTitle: "KYC pending",
  ribbonDescription: "Complete your KYC in Profile to activate services and avoid missing bookings.",
  ribbonAction: "Update KYC",
  pageTitle: "KYC Verification",
  statusPending: "Verification Pending",
  statusPendingDesc: "Your KYC documents are under review. This usually takes 1–2 business days.",
  statusVerified: "KYC Verified",
  statusVerifiedDesc: "Your identity has been verified. You can accept bookings and receive payouts.",
  statusRejected: "KYC Rejected",
  statusRejectedDesc: "Your KYC submission was rejected. Please review and resubmit.",
  sectionAadhaar: "Aadhaar Card",
  sectionPan: "PAN Card",
  sectionBank: "Bank Details",
  uploadFront: "Upload Front",
  uploadBack: "Upload Back",
  uploadDoc: "Upload Document",
  toastSubmitSuccess: "KYC submitted successfully",
  toastSubmitError: "Failed to submit KYC",
  toastUpdateSuccess: "KYC updated successfully",
  submitButton: "Submit KYC",
  updateButton: "Update KYC",
  stepAadhaar: "Aadhaar Card",
  stepPan: "PAN Card",
  stepBank: "Bank Details",
  stepPreview: "Review & Submit",
  termsAcceptance: "I accept the Terms and Conditions",
  nextButton: "Continue",
  backButton: "Back",
} as const;

export const KYC_SCHEMA_MESSAGES = {
  aadhaarRequired: "Aadhaar number is required",
  aadhaarInvalid: "Enter a valid 12-digit Aadhaar number",
  aadhaarFrontRequired: "Aadhaar front image is required",
  aadhaarBackRequired: "Aadhaar back image is required",
  panRequired: "PAN number is required",
  panInvalid: "Enter a valid PAN number (e.g. ABCDE1234F)",
  panDocRequired: "PAN card image is required",
  accountHolderRequired: "Account holder name is required",
  accountNumberRequired: "Account number is required",
  accountNumberInvalid: "Enter a valid account number (9–18 digits)",
  ifscRequired: "IFSC code is required",
  ifscInvalid: "Enter a valid IFSC code (e.g. SBIN0001234)",
  bankNameRequired: "Bank name is required",
} as const;
